# Лабораторная работа 2. Элементы линейной алгебры. Шаргин Иван

In [8]:
import numpy as np
import matplotlib.pyplot as plt

Решим СЛАУ A * u = f 

## 1. Метод Гаусса

Функция Gauss_solve реализует метод Гаусса, принимает на вход матрицу A, вектор правой части f, возвращает решение u

In [9]:
def Gauss_solve(A, f):
    """Функция Gauss_solve реализует метод Гаусса, 
    принимает на вход матрицу A, вектор правой части f, 
    возвращает решение u"""
    return Gauss_reverse(enumerate(straight_Gauss(A, f)))
    
    

In [13]:
def str_Gauss_step(A_f):
    """One step of the Gauss algorithm"""
    
    for i in range(1, A_f.shape[0]):
        k = A_f[i, 0] / A_f[0, 0]
        A_f[i, :] = A_f[i, :] - A_f[0, :] * k
    return A_f

In [63]:
def straight_Gauss(A, f):
    """Функция Gauss_solve реализует прямой метод Гаусса, 
    принимает на вход матрицу A, вектор правой части f, 
    возвращает кортеж (верхнетреугольная матрица, преобразованный вектор)"""
    leading_element_inds = np.transpose(np.nonzero(np.abs(A) == np.abs(A).max()))[0]
    A_f = np.hstack((A, f))
    A_f[[0, leading_element_inds[0]]] = A_f[[leading_element_inds[0], 0]]
    A_f[:, [0, leading_element_inds[1]]] = A_f[:, [leading_element_inds[1], 0]]
    
    for j in range(0, A_f.shape[0]):
        for i in range(j + 1, A_f.shape[0]):
            k = A_f[i, j] / A_f[j, j]
            A_f[i, j:] = A_f[i, j:] - A_f[j, j:] * k
            
#     for j in range(A_f.shape[0] - 1, 0, -1):
#         for i in range(j - 1, -1, -1):
#             k = A_f[i, j] / A_f[j, j]
#             A_f[i, :] = A_f[i, :] - A_f[j, :] * k
    
    
    return A_f    
    
 
   
    


In [51]:
for k in range(10, -1, -1):
    print(k)

10
9
8
7
6
5
4
3
2
1
0


In [64]:
A_test = np.array([[1, 0, 0 ], [0, 1, 0], [10, 0, 1]])
print(A_test)
f_test = np.array([[0.1], [0.2], [0.3]])
print(straight_Gauss(A_test, f_test))

[[ 1  0  0]
 [ 0  1  0]
 [10  0  1]]
[[10.    0.    1.    0.3 ]
 [ 0.    1.    0.    0.2 ]
 [ 0.    0.   -0.1   0.07]]


In [ ]:
def reverse_Gauss(R, f_):
     """Функция Gauss_solve реализует обратный ход метода Гаусса, 
    принимает на вход верхнетреугольную матрицу R, преобразованный 
    прямым ходом метода вектор правой части f_, 
    возвращает решение u"""
    

In [7]:
A = np.array([[1, 2, -300], [4, 5, 6], [7, -8, 0]])
leading_element_inds = np.transpose(np.nonzero(np.abs(A) == np.abs(A).max()))[0]
print(leading_element_inds)

[0 2]
